/*
# SYNGEn GREEN ARCHITECH - Products, Orders, Order Items

1. New Tables
- `products`: Agricultural products. Columns: id, name, category, description, use, price, image_url, is_new, is_upcoming, is_active, created_at, updated_at.
- `orders`: Customer orders. Columns: id, user_id, status, total, delivery_name, phone, created_at.
- `order_items`: Line items for orders. Columns: id, order_id, product_id, product_name, quantity, price, created_at.

2. Security
- RLS on all tables.
- Products: anyone can view active products; only admin can insert/update/delete.
- Orders: customers see their own; admins see all; customers can insert their own; only admin can update/delete.
- Order items: customers see items for their own orders; admins see all; customers can insert items for their own orders.

3. Seed Data
- 19 agricultural products across 4 categories.
*/

-- ============================================
-- PRODUCTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  description text DEFAULT '',
  use text DEFAULT '',
  price numeric DEFAULT 0,
  image_url text DEFAULT '',
  is_new boolean DEFAULT false,
  is_upcoming boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_select_active" ON public.products;
CREATE POLICY "products_select_active"
ON public.products FOR SELECT
TO anon, authenticated
USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "products_insert_admin" ON public.products;
CREATE POLICY "products_insert_admin"
ON public.products FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "products_update_admin" ON public.products;
CREATE POLICY "products_update_admin"
ON public.products FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "products_delete_admin" ON public.products;
CREATE POLICY "products_delete_admin"
ON public.products FOR DELETE
TO authenticated
USING (public.is_admin());

-- ============================================
-- ORDERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  total numeric DEFAULT 0,
  delivery_name text DEFAULT '',
  phone text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "orders_select_own_or_admin" ON public.orders;
CREATE POLICY "orders_select_own_or_admin"
ON public.orders FOR SELECT
TO authenticated
USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "orders_insert_own" ON public.orders;
CREATE POLICY "orders_insert_own"
ON public.orders FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_update_admin" ON public.orders;
CREATE POLICY "orders_update_admin"
ON public.orders FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "orders_delete_admin" ON public.orders;
CREATE POLICY "orders_delete_admin"
ON public.orders FOR DELETE
TO authenticated
USING (public.is_admin());

-- ============================================
-- ORDER_ITEMS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id),
  product_name text NOT NULL,
  quantity integer NOT NULL,
  price numeric NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "order_items_select_own_or_admin" ON public.order_items;
CREATE POLICY "order_items_select_own_or_admin"
ON public.order_items FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.orders o
    WHERE o.id = order_items.order_id
    AND (o.user_id = auth.uid() OR public.is_admin())
  )
);

DROP POLICY IF EXISTS "order_items_insert_own" ON public.order_items;
CREATE POLICY "order_items_insert_own"
ON public.order_items FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.orders o
    WHERE o.id = order_items.order_id
    AND o.user_id = auth.uid()
  )
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_is_new ON public.products(is_new);
CREATE INDEX IF NOT EXISTS idx_products_is_upcoming ON public.products(is_upcoming);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON public.order_items(product_id);

-- ============================================
-- UPDATED_AT trigger for products
-- ============================================
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS products_updated_at ON public.products;
CREATE TRIGGER products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================
-- SEED PRODUCTS
-- ============================================
INSERT INTO public.products (name, category, description, use, price, is_new, is_upcoming, is_active) VALUES
('WEEDKILL-58', 'Herbicides', 'Broad-spectrum systemic herbicide for effective weed control.', 'Apply on actively growing weeds for best results.', 0, false, false, true),
('GLYKILL-41', 'Herbicides', 'Non-selective herbicide targeting a wide range of weeds.', 'Use as a directed spray to avoid crop damage.', 0, false, false, true),
('OXYMAX', 'Herbicides', 'Selective herbicide for broadleaf weed management.', 'Apply post-emergence when weeds are small.', 0, false, false, true),
('ATRAZINE-50', 'Herbicides', 'Pre and post-emergence herbicide for grass and broadleaf weeds.', 'Incorporate into soil for residual control.', 0, false, false, true),
('RAZEL', 'Herbicides', 'Contact herbicide for fast-acting weed burn-down.', 'Spray directly on weed foliage.', 0, false, false, true),
('NUCLUEUS', 'Herbicides', 'Advanced systemic herbicide for tough perennial weeds.', 'Apply during active growth stage.', 0, false, false, true),
('M-75', 'Fungicides', 'Protectant fungicide for disease prevention.', 'Apply as a preventive spray before disease onset.', 0, false, false, true),
('SAFIX', 'Fungicides', 'Systemic fungicide for broad-spectrum disease control.', 'Use at first sign of fungal infection.', 0, false, false, true),
('BAVIST-ON', 'Fungicides', 'Curative fungicide for powdery mildew and rust.', 'Apply at early disease stage for best results.', 0, false, false, true),
('CHLOROX', 'Pesticides', 'Chlorine-based pesticide for soil treatment.', 'Apply to soil before planting for pest suppression.', 0, false, false, true),
('EMAXAM', 'Pesticides', 'Broad-spectrum insecticide for chewing pests.', 'Spray on affected crops at first pest sighting.', 0, false, false, true),
('CYPEROLE', 'Pesticides', 'Synthetic pyrethroid for contact insect control.', 'Apply in cool hours for maximum efficacy.', 0, false, false, true),
('FENGIN', 'Pesticides', 'Systemic insecticide for sap-feeding insects.', 'Use as soil drench or foliar spray.', 0, false, false, true),
('NUTRIFIX', 'Fertilizer', 'Balanced NPK fertilizer for overall crop nutrition.', 'Apply at basal and top-dressing stages.', 0, false, false, true),
('BOROFAST', 'Fertilizer', 'Boron micronutrient fertilizer for flowering crops.', 'Foliar spray during pre-flowering stage.', 0, false, false, true),
('CALBOFAST', 'Fertilizer', 'Calcium and boron combination for fruit development.', 'Apply during fruit set and development.', 0, false, false, true),
('COPERZEN', 'Fertilizer', 'Copper micronutrient for enzyme activation.', 'Use as foliar spray on deficient crops.', 0, false, false, true),
('FERAGRAIN', 'Fertilizer', 'Iron-chelated fertilizer for chlorosis correction.', 'Apply to soil or as foliar spray.', 0, false, false, true),
('ZINWOX', 'Fertilizer', 'Zinc micronutrient fertilizer for growth promotion.', 'Apply at early growth stages.', 0, false, false, true)
ON CONFLICT DO NOTHING;
